<?php

function miomodulo_help ($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.miomodulo':
     return 'questo è un hook help';
  }
}

function miomodulo_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) : void {
  if($form['#form_id'] !== 'node_page_form') {
    return;
  }
  if (isset($form['type']) && $form['type']['#value'] . '_node_settings' == $form_id) {
    $upload_enabled_types = \Drupal::config('my_module.settings')->get('upload_enabled_types');
    $form['workflow']['upload_' . $form['type']['#value']] = [
      '#type' => 'radios',
      '#title' => t('Attachments'),
      '#default_value' => in_array($form['type']['#value'], $upload_enabled_types) ? 1 : 0,
      '#options' => [
        t('Disabled'),
        t('Enabled'),
      ],
    ];
    // Add a custom submit handler to save the array of types back to the config
    // file.
    $form['actions']['submit']['#submit'][] = 'my_module_upload_enabled_types_submit';
  }
}